# Generated by Django 2.2.6 on 2019-11-01 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FRONT', 'Frontend'), ('BACK', 'Backend'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('view_status', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=2)),
                ('priority', models.CharField(choices=[('0', 'None'), ('1', 'Low'), ('2', 'Normal'), ('3', 'High'), ('4', 'Urgent'), ('5', 'Immediate')], default='0', max_length=2)),
                ('resolution', models.CharField(choices=[('0', 'Open'), ('1', 'Fixed'), ('2', 'Reopened'), ('3', 'Unable to reproduce'), ('4', 'Suspended')], default='0', max_length=1)),
                ('severity', models.CharField(choices=[('0', 'Feature'), ('1', 'Trivial'), ('2', 'Text'), ('3', 'Tweak'), ('4', 'Minor'), ('5', 'Major'), ('6', 'Crash'), ('7', 'Block')], default='0', max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('summary', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True, null=True)),
                ('reporter', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
