# Generated by Django 2.2.6 on 2019-11-03 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bug', '0002_auto_20191101_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='assigned_to',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bug',
            name='reporter',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporters', to=settings.AUTH_USER_MODEL),
        ),
    ]
