# Generated by Django 2.2.6 on 2019-11-03 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bug', '0003_auto_20191103_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='reporter',
        ),
        migrations.AddField(
            model_name='bug',
            name='author',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
    ]
